/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atminterface;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Yash Kathesia
 */
public class ATMInterface extends javax.swing.JFrame {

    private int PIN = 1526;
    private int accountBalance = 50000; // Assume that inital Balance is 50000Rs.

    /**
     * Creates new form ATMInterface
     */
    public ATMInterface() {
        initComponents();
        Image icon = new ImageIcon(this.getClass().getResource("/ATM_Logo.jpg")).getImage();
        // Set the icon image
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEnterPIN = new javax.swing.JLabel();
        enterPINField = new javax.swing.JTextField();
        btnEnter = new javax.swing.JButton();
        btnWithdrawl = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        btnViewBalance = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();
        lblBalance = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Close = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ATM Interface");

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("ATM");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblEnterPIN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblEnterPIN.setText("Enter PIN : ");

        enterPINField.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        enterPINField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enterPINField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterPINFieldActionPerformed(evt);
            }
        });

        btnEnter.setBackground(new java.awt.Color(102, 255, 102));
        btnEnter.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnEnter.setText("ENTER");
        btnEnter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        btnWithdrawl.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        btnWithdrawl.setText("Withdrawal");
        btnWithdrawl.setEnabled(false);
        btnWithdrawl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawlActionPerformed(evt);
            }
        });

        btnTransfer.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        btnTransfer.setText("Fund Transfer");
        btnTransfer.setEnabled(false);
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        btnViewBalance.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        btnViewBalance.setText("View Balance");
        btnViewBalance.setEnabled(false);
        btnViewBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBalanceActionPerformed(evt);
            }
        });

        btnDeposit.setFont(new java.awt.Font("Modern No. 20", 0, 18)); // NOI18N
        btnDeposit.setText("Deposit");
        btnDeposit.setEnabled(false);
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        lblBalance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnCancel.setText("CANCEL");
        btnCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        File.setText("File");

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        File.add(Close);

        jMenuBar1.add(File);

        jMenu2.setText("Help");

        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        jMenu2.add(About);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnEnter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEnterPIN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enterPINField))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDeposit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnViewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(btnWithdrawl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterPINField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWithdrawl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnter)
                    .addComponent(btnCancel))
                .addGap(45, 45, 45))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_CloseActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        JOptionPane.showMessageDialog(ATMInterface.this, "ATM Interface is Developed by Yash Kathesia.\nHope you will like !");
    }//GEN-LAST:event_AboutActionPerformed

    private void enterPINFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterPINFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterPINFieldActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed

        if (enterPINField.getText().matches("[0-9]+") == false) {
            JOptionPane.showMessageDialog(ATMInterface.this, "Please Enter PIN in Digits Only [0-9]");
            enterPINField.setText("");
        } else {
            int enteredPin = Integer.parseInt(enterPINField.getText());
            if (enteredPin == PIN) {
                btnEnter.setEnabled(false);
                btnWithdrawl.setEnabled(true);
                btnViewBalance.setEnabled(true);
                btnDeposit.setEnabled(true);
                btnTransfer.setEnabled(true);
                JOptionPane.showMessageDialog(ATMInterface.this, "PIN Verified Successfully...!!!");
                enterPINField.setText("");
                enterPINField.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(ATMInterface.this, "Invalid PIN!\nPlease Try Again...!!!");
                enterPINField.setText("");
            }
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed

        String accountNumberStr = JOptionPane.showInputDialog(ATMInterface.this, "Enter the account Number : ");
        int accountNumber = Integer.parseInt(accountNumberStr);
        String amountStr = JOptionPane.showInputDialog(ATMInterface.this, "Enter amount to deposit : ");
        int amount = Integer.parseInt(amountStr);
        if (amount <= accountBalance) {
            accountBalance -= amount;
            lblBalance.setText("Current Balance: Rs. " + accountBalance);
            JOptionPane.showMessageDialog(ATMInterface.this, amount + " Rs. is transfered successful to the account Number " + accountNumber + ".");
        } else {
            JOptionPane.showMessageDialog(ATMInterface.this, "Insufficient balance...!!!");
        }
    }//GEN-LAST:event_btnTransferActionPerformed

    private void btnViewBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBalanceActionPerformed
        lblBalance.setText("Current Balance: Rs. " + accountBalance);
    }//GEN-LAST:event_btnViewBalanceActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed

        String amountStr = JOptionPane.showInputDialog(ATMInterface.this, "Enter amount to deposit : ");
        float amount = Float.parseFloat(amountStr);
        accountBalance += amount;
        JOptionPane.showMessageDialog(ATMInterface.this, "Deposit Successful...!!!");
        lblBalance.setText("Current Balance: Rs. " + accountBalance);
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnWithdrawlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawlActionPerformed

        String amountStr = JOptionPane.showInputDialog(ATMInterface.this, "Enter Amount to withdraw : ");
        float amount = Float.parseFloat(amountStr);
        if (amount <= accountBalance) {
            accountBalance -= amount;
            JOptionPane.showMessageDialog(ATMInterface.this, "Withdrawal Successful...!!!");
            lblBalance.setText("Current Balance: Rs. " + accountBalance);
        } else {
            JOptionPane.showMessageDialog(ATMInterface.this, "Insufficient Balance...!!!");
        }
    }//GEN-LAST:event_btnWithdrawlActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        JOptionPane.showMessageDialog(ATMInterface.this, "Thank You for using this ATM!");
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATMInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenuItem Close;
    private javax.swing.JMenu File;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JButton btnViewBalance;
    private javax.swing.JButton btnWithdrawl;
    private javax.swing.JTextField enterPINField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblEnterPIN;
    // End of variables declaration//GEN-END:variables
}
